app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/registerlogin_db
    username: postgres
    password: password
    pool-size: 30

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: yukenautodev@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true